spring:
  application:
    name: forum

  mail:
    host: smtp.163.com
    port: 465
    username: 15823456412@163.com
    password: EJVT89zUzNLwmQXz
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forum
    username: root
    password: zxcvg123
  servlet:
    multipart:
          max-file-size: 10MB
          max-request-size: 10MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*.xml
jwt:
  secret: "dGhpcy1pcy1hLXN1cGVyLXNlY3JldC1rZXktMTIzNDU2Nzg5MAo="  # Base64 编码密钥
  expiration: 86400000  # 24 小时（单位：毫秒）
server:
  port: 8080
  servlet:
    context-path: /api
# 文件上传配置
file:
  upload-dir: c:/Users/23151/Desktop/后端/forum/uploads/images
  access-url: /images

